
source("createAdjacencyMatrix.R")
createVoteMatrix(110, ".")
print("calling cosponsors, Congress 110")
createCosponsMatrix(110, ".")
print("calling votes, Congress 111")
createVoteMatrix(111, ".")
print("calling cosponsors, Congress 111")
createCosponsMatrix(111, ".")
print("calling votes, Congress 112")
createVoteMatrix(112, ".")
print("calling cosponsors, Congress 112")
createCosponsMatrix(112, ".")
print("calling votes, Congress 113")
createVoteMatrix(113, ".")
print("calling cosponsors, Congress 113")
createCosponsMatrix(113, ".")
